"use strict";
// Burnlink CLI splash renderer.
//
// Strategy:
//   1. If `assets/logo.png` exists AND stdout is a truecolor TTY → render
//      the actual PNG as ANSI truecolor block art (the same approach as
//      `viu` / `img2text` / `chafa`).
//   2. Otherwise → fall back to the figlet "Standard" wordmark "Burnlink"
//      + a hand-drawn flame glyph, both in the brand orange.
//
// Both paths honour `NO_COLOR` and `--no-color` and degrade to plain text
// when stdout is not a TTY (so pipes / CI logs aren't polluted with
// escape codes).
//
// The WORDMARK constant below was generated with the figlet npm package
// (font: "Standard", width: 200) and baked here so the CLI doesn't need
// figlet as a runtime dep. To regenerate after a brand rename:
//
//   node -e 'const f=require("figlet");process.stdout.write(f.textSync("Burnlink",{font:"Standard",width:200}))'
//
// then paste the output back into WORDMARK.

const fs = require("node:fs");
const path = require("node:path");
const brand = require("./brand");

const RESET = "\x1b[0m";
const DIM = "\x1b[2m";
const BOLD = "\x1b[1m";

// Brand palette pulled from ./brand.js (which mirrors the website's CSS).
//   primary:   #eb583d  — flame orange, links, focus, QR buttons
//   secondary: #ff8c42  — gradient pair, info toasts
const ORANGE = brand.ANSI.primary;
const ORANGE_LIGHT = brand.ANSI.secondary;

const TTY =
  !!process.stdout.isTTY &&
  !process.env.NO_COLOR &&
  !process.env.CI &&
  process.env.TERM !== "dumb";

const TRUECOLOR = (() => {
  if (!TTY) return false;
  const ct = (process.env.COLORTERM || "").toLowerCase();
  return ct === "truecolor" || ct === "24bit";
})();

// ---- ASCII fallback: wordmark + flame glyph ----------------------------

// "Burnlink" in figlet "Standard" font (40 cols x 6 rows). Generated by
// the figlet npm package at build time; baked here so the CLI doesn't
// need figlet as a runtime dep. ASCII-only.
const WORDMARK = [
  "  ____                   _ _       _    ",
  " | __ ) _   _ _ __ _ __ | (_)_ __ | | __",
  " |  _ \\| | | | '__| '_ \\| | | '_ \\| |/ /",
  " | |_) | |_| | |  | | | | | | | | |   < ",
  " |____/ \\__,_|_|  |_| |_|_|_|_| |_|_|\\_\\",
  "                                        ",
];

// 6-row flame glyph evoking the public/logo1.png silhouette.
const FLAME = [
  "   .   ",
  "  /|\\  ",
  " / | \\ ",
  "/  |  \\",
  "'. _ .'",
  "  ' '  ",
];

function pad(s, w) {
  const visible = s.replace(/\x1b\[[0-9;]*m/g, "");
  if (visible.length >= w) return s;
  return s + " ".repeat(w - visible.length);
}

function colorize(rows, color, enabled) {
  return enabled ? rows.map((r) => color + r + RESET) : rows;
}

function asciiSplash({ version, plan, fingerprint, repo }) {
  const wm = colorize(WORDMARK, ORANGE, TTY);
  const fl = colorize(FLAME, ORANGE, TTY);
  const wmHeight = wm.length;
  const flHeight = fl.length;
  const flameOffset = Math.floor((wmHeight - flHeight) / 2);
  const wmWidth = WORDMARK[0].length;
  const rows = ["", ""];
  for (let i = 0; i < wmHeight; i++) {
    const fr = i - flameOffset;
    const left =
      fr >= 0 && fr < flHeight
        ? pad(fl[fr], 7)
        : " ".repeat(7);
    rows.push(left + wm[i]);
  }
  rows.push("");
  rows.push(pad(`  Privacy-first file sharing, end-to-end encrypted.`, wmWidth));
  rows.push(pad(`  ${DIM}v${version}${RESET}  ·  ${plan ? `${DIM}${plan} license active${RESET}` : `${DIM}free tier${RESET}`}  ·  ${DIM}${repo}${RESET}`));
  rows.push("");
  rows.push(`  ${BOLD}Usage${RESET}    ${ORANGE}burnlink${RESET} ${DIM}<command> [options]${RESET}`);
  rows.push(`  ${BOLD}Quick start${RESET}`);
  rows.push(`    ${ORANGE}burnlink upload${RESET} ${DIM}<file>${RESET}      share a file`);
  rows.push(`    ${ORANGE}burnlink download${RESET} ${DIM}<url>${RESET}     receive a file`);
  rows.push(`    ${ORANGE}burnlink status${RESET}              show license + config`);
  rows.push(`    ${ORANGE}burnlink help${RESET}                full command list`);
  rows.push("");
  if (fingerprint) {
    rows.push(`  ${DIM}License fingerprint: ${fingerprint}${RESET}`);
    rows.push("");
  }
  return rows.join("\n");
}

// ---- PNG truecolor path ------------------------------------------------

function pngSplash(pngPath, meta) {
  const { renderPNGtoANSI } = require("./img-to-ansi");
  const buf = fs.readFileSync(pngPath);
  const logoCols = 22;
  const logo = renderPNGtoANSI(buf, { maxCols: logoCols }).split("\n");
  const wm = colorize(WORDMARK, ORANGE, TTY);
  const wmCols = WORDMARK[0].length;
  const wmHeight = wm.length;
  const logoHeight = logo.length;
  // Center the logo vertically against the wordmark. The figlet wordmark
  // is 6 rows tall with a blank descender row; logo gets a top offset so
  // the visual center of the flame aligns with the visual center of the
  // wordmark (slightly above geometric center, since the blank descender
  // row adds visual weight to the bottom).
  const logoOffset = Math.max(0, Math.floor((wmHeight - logoHeight) / 2) - 1);
  const rows = [];
  rows.push("");
  for (let i = 0; i < wmHeight; i++) {
    const li = i - logoOffset;
    const l = li >= 0 && li < logoHeight ? logo[li] : "";
    rows.push(pad(l, logoCols + 2) + wm[i]);
  }
  rows.push("");
  rows.push(
    pad(
      `  Privacy-first file sharing, end-to-end encrypted.`,
      wmCols + logoCols + 2,
    ),
  );
  rows.push(
    pad(
      `  ${DIM}v${meta.version}${RESET}  ·  ${meta.plan ? `${DIM}${meta.plan} license active${RESET}` : `${DIM}free tier${RESET}`}  ·  ${DIM}${meta.repo}${RESET}`,
      wmCols + logoCols + 2,
    ),
  );
  rows.push("");
  rows.push(
    `  ${BOLD}Usage${RESET}    ${ORANGE}burnlink${RESET} ${DIM}<command> [options]${RESET}`,
  );
  rows.push(`  ${BOLD}Quick start${RESET}`);
  rows.push(
    `    ${ORANGE}burnlink upload${RESET} ${DIM}<file>${RESET}      share a file`,
  );
  rows.push(
    `    ${ORANGE}burnlink download${RESET} ${DIM}<url>${RESET}     receive a file`,
  );
  rows.push(
    `    ${ORANGE}burnlink status${RESET}              show license + config`,
  );
  rows.push(
    `    ${ORANGE}burnlink help${RESET}                full command list`,
  );
  rows.push("");
  if (meta.fingerprint) {
    rows.push(`  ${DIM}License fingerprint: ${meta.fingerprint}${RESET}`);
    rows.push("");
  }
  return rows.join("\n");
}

// ---- Public API --------------------------------------------------------

function renderSplash({ version, plan, fingerprint, repo }) {
  const meta = { version, plan, fingerprint, repo };
  // Look for a bundled logo.png next to this module: ../../assets/logo.png
  // (CLI repo layout: src/ascii-logo.js, assets/logo.png in the same package).
  const candidates = [
    path.resolve(__dirname, "..", "assets", "logo.png"),
    path.resolve(__dirname, "..", "..", "assets", "logo.png"),
    path.resolve(process.cwd(), "assets", "logo.png"),
  ];
  if (TRUECOLOR) {
    for (const p of candidates) {
      if (fs.existsSync(p)) {
        try {
          return pngSplash(p, meta);
        } catch (e) {
          // PNG decode failed — fall through to ASCII.
        }
      }
    }
  }
  return asciiSplash(meta);
}

module.exports = { renderSplash, asciiSplash, pngSplash, FLAME, WORDMARK, ORANGE };

// Self-test (run via `node src/ascii-logo.js`):
// verifies the baked wordmark is structurally valid. The figlet "Standard"
// font draws letters from a glyph table (no literal ASCII letters appear in
// the output), so the only verifiable invariants are: equal row widths,
// ASCII-only content, expected glyph vocabulary, expected height. Visual
// legibility ("does this read as Burnlink?") is left to the human eye.
if (require.main === module) {
  const width = WORDMARK[0].length;
  for (let i = 0; i < WORDMARK.length; i++) {
    if (WORDMARK[i].length !== width) {
      console.error(`WORDMARK row ${i} is ${WORDMARK[i].length} cols, expected ${width}`);
      process.exit(1);
    }
  }
  // ASCII-only check.
  for (let i = 0; i < WORDMARK.length; i++) {
    if (!/^[\x20-\x7e]+$/.test(WORDMARK[i])) {
      console.error(`WORDMARK row ${i} contains non-ASCII chars`);
      process.exit(1);
    }
  }
  // figlet's "Standard" font uses this restricted glyph vocabulary.
  const ALLOWED = new Set(" '(),/<>_\\|");
  for (let i = 0; i < WORDMARK.length; i++) {
    for (const ch of WORDMARK[i]) {
      if (!ALLOWED.has(ch)) {
        console.error(`WORDMARK row ${i} contains unexpected char ${JSON.stringify(ch)}`);
        process.exit(1);
      }
    }
  }
  // Expected row count for figlet's "Standard" font is 6.
  if (WORDMARK.length !== 6) {
    console.error(`WORDMARK height is ${WORDMARK.length}, expected 6`);
    process.exit(1);
  }
  console.log("WORDMARK OK —", WORDMARK.length, "rows x", width, "cols, ASCII-only, glyph vocab matches figlet Standard");
  console.log("");
  console.log(asciiSplash({ version: "0.0.0", plan: null, fingerprint: null, repo: "x" }));
}